# Tomcat
server:
  port: 8881
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    min-spare-threads: 10
  servlet:
    context-path: /center

# spring
spring:
  application:
    name: server-center

# eureka
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}${server.servlet.context-path}/eureka/