server:
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/center/eureka/

spring:
  application:
    name: shop-front-web
  redis:
    port: 6379
    database: 1
    timeout: 10000
    host: cloud.mz99.shop
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 20
        min-idle: 5

feign:
  hystrix:
    enabled: true

# https://docs.spring.io/spring-boot/docs/2.1.3.RELEASE/reference/htmlsingle/#configuration-metadata-format
geetest:
  captchaId: 3db49959bbb8490edc2adb0af5b0d2e6
  privateKey: 9d540015f27a68e3e8b76ea66eb53f36
