server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/center/eureka/

spring:
  application:
    name: shop-sso
  redis:
    port: 6379
    database: 1
    timeout: 10000
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 20
        min-idle: 5

sso:
  session:
    expire: 1800
